### Write a function so that the columns of the output matrix are powers of the input vector.
### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [1]:
import numpy as np

In [23]:
def gen_vander_mat(ipv, n, increasing = False):
    if not increasing:
        matx = np.array([x**(n-i-1) for x in ipv for i in range(n)]).reshape(ipv.size, n)
    elif increasing:
        matx = np.array([x**i for x in ipv for i in range(n)]).reshape(ipv.size, n)
                        
    return matx

In [24]:
ipv = np.array([1,2,3])
n = 3
gen_vander_mat(ipv, n)

array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]])

In [25]:
ipv = np.array([1,2,3,4])
n = 4
gen_vander_mat(ipv, n)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [26]:
ipv = np.array([1,2,3,4])
n = 4
gen_vander_mat(ipv, n, True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

# Write a function to find moving average in an array over a window:
# Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [45]:
def movingAvg(list, k):
    n=len(list) - k + 1
    mv = []
    s=0
    
    for i in range(n):
        s=0
        for j in range(i,i+k):
            s+=list[j]         
        mv.append(int(s/k))
    
    return mv

In [46]:
l = [10,20,30,40,50,60]
k = 4
movingAvg(l,k)

[25, 35, 45]

In [47]:
l = [10,20,30,40,50,60]
k = 3
movingAvg(l,k)

[20, 30, 40, 50]

In [48]:
l = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3
movingAvg(l,k)

[5, 4, 5, 6, 9, 28, 49, 72, 84, 93, 116]